### ISSUE TITLE
deque instead of Queue

### ISSUE THREAD

**Issue by danielhrisca** [christoph2/pyxcp#31]
Hello,

I'm having a case were using _queue.Queue_ results in packets lost (CarMaker simulation running at ~2.5x and acquiring many signals). 

Using _collections.deque_ alleviates this problem.

**Comment by christoph2** [comment]
Hello Daniel, 
Great to hear from you again! 
Well,  I've written some benchmarks and really was surprised about the performance penalty of queue.Queue... 
As a first step I'm now using collections.deque . 
But I think the root cause of all evil is these awful threading stuff -- I have added asyncIO on top of my TODO list.
